FROM alpine:latest

RUN apk add --no-cache curl python3 py3-pip; \
    pip3 install awscli; \
    rm -rf /var/cache/apk/*; \
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp; \
    mv /tmp/eksctl /usr/local/bin; \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl; \
    chmod u+x kubectl && mv kubectl /bin/kubectl

# ENTRYPOINT [""]
CMD ["sh"]